import Head from 'next/head'
import {Box, Link, Image, Heading, Text, Flex, Container, useColorMode,} from '@chakra-ui/react'
import fetch from 'isomorphic-unfetch';

export default function Home({ notes}) {
  return (
    <div>
      <Head>
        <title>Word Treasures</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex display="flex" justify="center" align="center" direction="column" background="teal.200" h={'87vh'} >
        <Heading m={5}>Welcome to Word Treasures</Heading>


        {
          notes.map (note =>{
          return(
            <Flex p={5} w="300px" h="400px" key={note._id} justify="center" direction="column" borderRadius={20} boxShadow="dark-lg" background="white">
                <Link href={`/${note._id}` }>
                  <Heading  p={5} as='h2' size='lg'>{note.verse}</Heading>
                    <Flex p={5} d="flex" justify="space-between" direction="column" >
                   
                    <Heading size="md">Message:</Heading>
                    
                    <Text mb={1} size='md'>{note.message}</Text>
                    <Heading>Application:</Heading>
                    <Text mb={1} size='md'>{note.application}</Text>
                    </Flex>
                  
                </Link>
           </Flex>
          )
        })

        }
       

      </Flex>
     
    </div>
  )
}

Home.getInitialProps = async () => {
  const res = await fetch('http://localhost:3000/api/notes/')
  const { data } = await res.json()

  return{notes: data}
}
